### ISSUE TITLE
Traducir mensaje GAME OVER en juego PONG

### ISSUE THREAD

**Issue by guillermopalazon** [guillermopalazon/practicaJuegoED20212022#9]
En ping.js traducir los mensajes de GAME OVER Y click to reload A ESPAÑOL (líneas 185 y 186)

**Comment by JuMaSe23** [comment]
Se han traducido los mensajes GAME OVER y CLICK TO RELOAD de las líneas 185 y 186 de ping.js a castellano en la rama Tarea9, que posteriormente ha sido fusionada con la rama Master, por lo que esta issue ha sido resuelta satisfactoriamente
